#!/bin/bash
clear

# Edit /etc/pacman.conf file
nano /etc/pacman.conf
clear

# Update archlinux-keyring package
pacman -Sy archlinux-keyring
clear

# Disk Configuration
lsblk
echo ' '
read -p 'Select Disk (Example: vda, sda, nvme0n1): ' disk_selection
cfdisk /dev/$disk_selection

clear
lsblk
echo ' '

# Format disk label
read -p 'Root partition (Example: vda1, sda1, nvme0n1p1): ' root_partition
mkfs.ext4 /dev/$root_partition
mount /dev/$root_partition /mnt
sleep 2

clear

lsblk
echo ' '
read -p 'Boot partition (Example: vda1, sda1, nvme0n1p1): ' boot_partition
mkfs.fat -F32 /dev/$boot_partition
mkdir -p /mnt/boot/efi

clear

# Install base arch linux packages
pacstrap -i /mnt base base-devel linux linux-headers linux-firmware git nano

# Create fstab file
genfstab -U /mnt > /mnt/etc/fstab
mount /dev/$boot_partition /mnt/boot/efi
clear

# Arch Install script backup
mkdir -p /mnt/root/arch-install-backup
cp -rv $(pwd)/archinstall /mnt/root/arch-install-backup
cp -rv $(pwd)/chroot /mnt/root/arch-install-backup
ln -s /mnt/root/arch-install-backup/chroot /mnt/chroot

# Chroot Environment
arch-chroot /mnt /bin/bash
rm -rf /mnt/archinstall
rm -rf /mnt/chroot
