#!/bin/bash
clear

# Edit /etc/pacman.conf file
nano /etc/pacman.conf

clear

# Timezone
echo 'Example: Europe/Istanbul, Europe/Zurich, America/New_York'
read -p 'Timezone: ' time_zone
ln -sf /usr/share/zoneinfo/$time_zone /etc/localtime
hwclock --systohc

clear

read -p "Select locale [en/tr]: " localeset

if [ $localeset == "en" ];
then
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
    locale-gen
    touch /etc/locale.conf
    echo "LANG=en_US.UTF-8" >> /etc/locale.conf
    touch /etc/vconsole.conf
    echo "KEYMAP=us" >> /etc/vconsole.conf
else
    echo "tr_TR.UTF-8 UTF-8" >> /etc/locale.gen
    locale-gen
    touch /etc/locale.conf
    echo "LANG=tr_TR.UTF-8" >> /etc/locale.conf
    touch /etc/vconsole.conf
    echo "KEYMAP=trq" >> /etc/vconsole.conf
fi

clear

# Hosts, hostname
read -p 'Hostname: ' host_name
echo $host_name >> /etc/hostname

echo "127.0.0.1       localhost" >> /etc/hosts
echo "::1             localhost" >> /etc/hosts
echo "127.0.1.1       $host_name.localdomain     $host_name" >> /etc/hosts

clear

# Root password
echo 'Root password'
passwd
sleep 2

clear

# NetworkManager
pacman -Sy networkmanager
systemctl enable NetworkManager
sleep 2
clear

# Touchpad Support
pacman -S xf86-input-libinput
sleep 2
clear

# NTFS filesystem support
pacman -S ntfs-3g
sleep 2
clear

# GRUB
pacman -S grub efibootmgr os-prober
sleep 2
clear

grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id='Arch Linux'
sleep 2
clear

grub-mkconfig -o /boot/grub/grub.cfg
sleep 3
clear

# Add user
read -p 'Username: ' user_name
clear

useradd -m -g users -G wheel,storage,power,audio,video,network -s /bin/bash $user_name
echo $user_name 'password'
passwd $user_name
sleep 2

# sudo privileges
EDITOR=nano visudo
clear

# Arch Install script backup
read -p "Do you want to backup your Arch Install script? [y/n]: " backup_arch_install

if [ $backup_arch_install == "y" ]; then
    echo "Arch Install script is already saved in '/root/arch-install-backup' folder. No action was taken."
    exit 0
elif [ $backup_arch_install == "Y" ]; then
    echo "Arch Install script is already saved in '/root/arch-install-backup' folder. No action was taken."
    exit 0
elif [ $backup_arch_install == "n" ]; then
    rm -rfv /root/arch-install-backup 
    echo "Arch Install script removed from '/root/arch-install-backup' folder"
    exit 0
elif [ $backup_arch_install == "N" ]; then
    rm -rfv /root/arch-install-backup 
    echo "Arch Install script removed from '/root/arch-install-backup' folder"
    exit 0
else
    echo "By default Arch Install script is saved in '/root/arch-install-backup' folder. You have not selected any action. If you want to delete it, you can delete the '/root/arch-install-backup' folder"
    exit 0
fi
